export interface ICurrentUser {
    id: string | undefined,
    email: string | undefined,
    name: string | undefined,
    lastName: string | undefined,
    avatar: string | undefined,
    likeCounter: string ,
    dislikeCounter: string,
    subscriptions: string[],
    subscribers: string[],
    theme: string | undefined,
    instagram: string | undefined,
    facebook: string | undefined,
    twitter: string | undefined,
    spotify: string | undefined,
    telegram: string | undefined,
    github: string | undefined,
    soundCloud: string | undefined,
    youTube: string | undefined,
}